# Site settings
title: Simply 5G Security
email: pienvandenabeele@gmail.com
description: >
  Making 5G Security accessible for everyone!
lang: en-UK

baseurl: "/Simply5GSecurity" # the subpath of your site, e.g. /blog/
url: https://pienvandenabeele.github.io/Simply5GSecurity # the base hostname & protocol for your site
git_address: https://pienvandenabeele.github.io/Simply5GSecurity
git_edit_address: https://pienvandenabeele.github.io/Simply5GSecurity/blob/gh-pages

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: sandstone # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
timezone: Europe/Amsterdam
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true

remote_theme: aksakalli/jekyll-doc-theme@gh-pages 
